name: Check Links

on:
  # Run on push to the main branch
  workflow_dispatch:
  schedule:
    # Run once a day at midnight
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout wiki repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: .wiki

      # Use the lychee action to check links
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # Check all markdown and HTML files in the repo
          args: --verbose --no-progress './**/*.md' './**/*.html'
          # Use json output format for GitHub annotations
          format: json
          # Create a new GitHub issue when there are broken links
          fail: true
          jobSummary: true
          
      # Upload the link report as an artifact
      - name: Upload link check report
        uses: actions/upload-artifact@v3
        with:
          name: link-check-report
          path: lychee/out.json
